name: date_time_format
description: A utility class for formatting DateTimes.
version: 0.1.0+1
homepage: https://github.com/james-alex/date_time_format

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  test: ^1.12.0

dev_dependencies:
  effective_dart: ^1.2.1
